services:
  ache:
    image: vidanyu/ache
    command: startCrawl -c /config/ -s /config/tor.seeds -o /data -e tor
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms48g -Xmx64g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=16 -XX:ConcGCThreads=8 -XX:G1HeapRegionSize=32m
    deploy:
      resources:
        limits:
          cpus: '16'
          memory: 96G
        reservations:
          cpus: '12'
          memory: 80G
        restart_policy:
          condition: any
          delay: 12h
          max_attempts: 3
          window: 120s
    volumes:
      # mounts /config and /data directories to paths relative to path where this file is located
      - ./data-ache/:/data
      - ./:/config
    depends_on:
      - torproxy
      - elasticsearch
  # Main DB
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - ES_JAVA_OPTS=-Xms56g -Xmx56g -XX:+UseG1GC -XX:G1HeapRegionSize=32m
      - indices.memory.index_buffer_size=25%
      - thread_pool.write.queue_size=4000
      - thread_pool.search.queue_size=4000
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 131072
        hard: 131072
    deploy:
      resources:
        limits:
          cpus: '12'
          memory: 120G
        reservations:
          cpus: '8'
          memory: 64G
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
    volumes:
      - elastic_volume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  
  # Tor proxy
  torproxy:
    image: dperson/torproxy
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  elastic_volume: