services:
  ache:
    image: vidanyu/ache
    command: startCrawl -c /config/ -s /config/tor.seeds -o /data -e tor
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - JAVA_OPTS=-Xms${MIN_RAM}g -Xmx${MAX_RAM}g
    volumes:
      # mounts /config and /data directories to paths relative to path where this file is located
      - ./data-ache/:/data
      - ./:/config
    links:
      - torproxy1
      - torproxy2
      - elasticsearch
    depends_on:
      - torproxy1
      - torproxy2
      - elasticsearch
  # Main DB
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    env_file:
      - ./.env
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms${MIN_RAM}g -Xmx${MAX_RAM}g # Heap size
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_volume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      
  torproxy:
    image: dperson/torproxy
        - torproxy1
        - torproxy2
    ports:
      - "8118:8118"

  haproxy:
    image: haproxy:latest
    ports:
      - "8888:8888"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - torproxy1
      - torproxy2

volumes:
  elastic_volume: